//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanBooks.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrbanBooks.Common.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is Required..
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to change project status?.
        /// </summary>
        public static string Areyousurewanttochangeprojectstatus {
            get {
                return ResourceManager.GetString("Areyousurewanttochangeprojectstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Sure You Want To Change Status Of Customer?.
        /// </summary>
        public static string AreyouSureYouWantToChangeStatusOfCustomer {
            get {
                return ResourceManager.GetString("AreyouSureYouWantToChangeStatusOfCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change status of user.
        /// </summary>
        public static string AreyouSureYouWantToChangeStatusOfUser {
            get {
                return ResourceManager.GetString("AreyouSureYouWantToChangeStatusOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To is Required.
        /// </summary>
        public static string AssignToRequired {
            get {
                return ResourceManager.GetString("AssignToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name is Required..
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments is Required.
        /// </summary>
        public static string Commentsrequired {
            get {
                return ResourceManager.GetString("Commentsrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is Required.
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conatact Person is Required..
        /// </summary>
        public static string ConatactPersonRequired {
            get {
                return ResourceManager.GetString("ConatactPersonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is Required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name is Required.
        /// </summary>
        public static string ContactNameRequired {
            get {
                return ResourceManager.GetString("ContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Saved Successfully..
        /// </summary>
        public static string ContactSavedSuccessfully {
            get {
                return ResourceManager.GetString("ContactSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Source Deleted Successfully..
        /// </summary>
        public static string ContactSouceDeletedSuccesffully {
            get {
                return ResourceManager.GetString("ContactSouceDeletedSuccesffully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Source is Required.
        /// </summary>
        public static string ContactSourceRequired {
            get {
                return ResourceManager.GetString("ContactSourceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Source Saved Successfully..
        /// </summary>
        public static string ContactSourceSavedSuccessfully {
            get {
                return ResourceManager.GetString("ContactSourceSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Source Updated Successfully..
        /// </summary>
        public static string ContactSourceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ContactSourceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Updated Successfully..
        /// </summary>
        public static string ContactUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ContactUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is Required.
        /// </summary>
        public static string CountryNameRequired {
            get {
                return ResourceManager.GetString("CountryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status is Required.
        /// </summary>
        public static string CurrentStatusRequired {
            get {
                return ResourceManager.GetString("CurrentStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is Required.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DELETE statement conflicted with the REFERENCE constraint.
        /// </summary>
        public static string DeleteStatementConflict {
            get {
                return ResourceManager.GetString("DeleteStatementConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is Required.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Deleted Successfully..
        /// </summary>
        public static string DesignationDeletedsuccessfully {
            get {
                return ResourceManager.GetString("DesignationDeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is Required.
        /// </summary>
        public static string DesignationRequired {
            get {
                return ResourceManager.GetString("DesignationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Saved Successfully..
        /// </summary>
        public static string DesignationSavedSuccessfully {
            get {
                return ResourceManager.GetString("DesignationSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Updated Successfully..
        /// </summary>
        public static string DesignationUpdatedsuccessfully {
            get {
                return ResourceManager.GetString("DesignationUpdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Deleted Successfully..
        /// </summary>
        public static string DomainDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DomainDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name is Required.
        /// </summary>
        public static string DomainRequired {
            get {
                return ResourceManager.GetString("DomainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Saved Successfully..
        /// </summary>
        public static string DomainSavedsuccessfully {
            get {
                return ResourceManager.GetString("DomainSavedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Updated Successfully..
        /// </summary>
        public static string DomainUpdatedsuccessfully {
            get {
                return ResourceManager.GetString("DomainUpdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Already Exists!.
        /// </summary>
        public static string EmailAddressAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is Required.
        /// </summary>
        public static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Body is Required..
        /// </summary>
        public static string EmailBodyRequired {
            get {
                return ResourceManager.GetString("EmailBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email Address.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Subject is Required..
        /// </summary>
        public static string EmailSubjectRequired {
            get {
                return ResourceManager.GetString("EmailSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid First Name.
        /// </summary>
        public static string FirstNameInvalid {
            get {
                return ResourceManager.GetString("FirstNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Details Not Saved!.
        /// </summary>
        public static string FollowUpDetailsNotSaved {
            get {
                return ResourceManager.GetString("FollowUpDetailsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Details Saved Successfully..
        /// </summary>
        public static string FollowUpDetailsSavedSuccessfully {
            get {
                return ResourceManager.GetString("FollowUpDetailsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Details Updated Successfully..
        /// </summary>
        public static string FollowUpDetailsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("FollowUpDetailsUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Type Deleted Successfully..
        /// </summary>
        public static string Followuptypedeletedsuccessfully {
            get {
                return ResourceManager.GetString("Followuptypedeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Type is Required.
        /// </summary>
        public static string FollowUpTypeRequired {
            get {
                return ResourceManager.GetString("FollowUpTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Type Saved Successfully..
        /// </summary>
        public static string Followuptypesavedsuccefully {
            get {
                return ResourceManager.GetString("Followuptypesavedsuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Type Updated Successfully..
        /// </summary>
        public static string Followuptypeupdatedsuccessfully {
            get {
                return ResourceManager.GetString("Followuptypeupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is Requried.
        /// </summary>
        public static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email Required..
        /// </summary>
        public static string FromEmailRequired {
            get {
                return ResourceManager.GetString("FromEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Contains Numbers Only.
        /// </summary>
        public static string HoursContainsNumbersonly {
            get {
                return ResourceManager.GetString("HoursContainsNumbersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours is Required.
        /// </summary>
        public static string Hoursisrequire {
            get {
                return ResourceManager.GetString("Hoursisrequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File!.
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login details!.
        /// </summary>
        public static string InvalidLoginDetails {
            get {
                return ResourceManager.GetString("InvalidLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Post code.
        /// </summary>
        public static string InvalidPostCode {
            get {
                return ResourceManager.GetString("InvalidPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is Invalid..
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Last Name.
        /// </summary>
        public static string LastNameInvalid {
            get {
                return ResourceManager.GetString("LastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sent Successfully..
        /// </summary>
        public static string MailSentSuccessfully {
            get {
                return ResourceManager.GetString("MailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messanger Id is Required.
        /// </summary>
        public static string MessangersIdRequired {
            get {
                return ResourceManager.GetString("MessangersIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messanger Type Deleted Successfully..
        /// </summary>
        public static string Messangertypedeletedsuccessfully {
            get {
                return ResourceManager.GetString("Messangertypedeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messanger Type is Required.
        /// </summary>
        public static string MessangerTypeRequired {
            get {
                return ResourceManager.GetString("MessangerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messanger Type Saved Successfully..
        /// </summary>
        public static string MessangertypesavedSuccessfully {
            get {
                return ResourceManager.GetString("MessangertypesavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messanger Type Updated Successfully..
        /// </summary>
        public static string MessangertypeUpdatedsuccessfully {
            get {
                return ResourceManager.GetString("MessangertypeUpdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Mobile Number.
        /// </summary>
        public static string MobileNoInvalid {
            get {
                return ResourceManager.GetString("MobileNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is Required.
        /// </summary>
        public static string MobileNoRequired {
            get {
                return ResourceManager.GetString("MobileNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string NewandConfirmShouldbeSame {
            get {
                return ResourceManager.GetString("NewandConfirmShouldbeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is Required.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Saved Successfully..
        /// </summary>
        public static string NewsletterSavedSuccessfully {
            get {
                return ResourceManager.GetString("NewsletterSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Updated Successfully..
        /// </summary>
        public static string NewsletterUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("NewsletterUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NextFollowUpDate is Required.
        /// </summary>
        public static string NextFollowUpDaterequired {
            get {
                return ResourceManager.GetString("NextFollowUpDaterequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Details NotSaved..
        /// </summary>
        public static string NoteDetailsNotSaved {
            get {
                return ResourceManager.GetString("NoteDetailsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Details Saved Successfully..
        /// </summary>
        public static string NoteDetailsSavedSuccessfully {
            get {
                return ResourceManager.GetString("NoteDetailsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Details Updated Successfully..
        /// </summary>
        public static string NoteDetailsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("NoteDetailsUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Old Password.
        /// </summary>
        public static string OldPasswordNotMatch {
            get {
                return ResourceManager.GetString("OldPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is Required.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully. .
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Password.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Phone No.
        /// </summary>
        public static string PhoneNoInvalid {
            get {
                return ResourceManager.GetString("PhoneNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select contact(s) to assign.
        /// </summary>
        public static string PleaseSelectContactToAssign {
            get {
                return ResourceManager.GetString("PleaseSelectContactToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Contact.
        /// </summary>
        public static string PleaseSelectTheContact {
            get {
                return ResourceManager.GetString("PleaseSelectTheContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Technology is Required.
        /// </summary>
        public static string PrimaryTechnologyRequired {
            get {
                return ResourceManager.GetString("PrimaryTechnologyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated Successfully..
        /// </summary>
        public static string ProfileUpdatedSuccessfullly {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfullly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description is Required.
        /// </summary>
        public static string ProjectDescriptionrequired {
            get {
                return ResourceManager.GetString("ProjectDescriptionrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details Saved Successfully...
        /// </summary>
        public static string ProjectDetailsSavedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectDetailsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Technology is Required.
        /// </summary>
        public static string ProjectTechonologyrequire {
            get {
                return ResourceManager.GetString("ProjectTechonologyrequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title is Required.
        /// </summary>
        public static string ProjectTitleisRequire {
            get {
                return ResourceManager.GetString("ProjectTitleisRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question is Required..
        /// </summary>
        public static string QuestionRequired {
            get {
                return ResourceManager.GetString("QuestionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings is Required.
        /// </summary>
        public static string RatingsRequired {
            get {
                return ResourceManager.GetString("RatingsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Assign To is Required.
        /// </summary>
        public static string ReAssignedToRequired {
            get {
                return ResourceManager.GetString("ReAssignedToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record link to another record(s), you can not delete this record.
        /// </summary>
        public static string RecordCannotBeDeleted {
            get {
                return ResourceManager.GetString("RecordCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting To is Required.
        /// </summary>
        public static string ReportingToRequired {
            get {
                return ResourceManager.GetString("ReportingToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is Required.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file for import.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid File..
        /// </summary>
        public static string SelectValidFile {
            get {
                return ResourceManager.GetString("SelectValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Status is Required..
        /// </summary>
        public static string SentStatusRequired {
            get {
                return ResourceManager.GetString("SentStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has timed out! Please login again to continue..
        /// </summary>
        public static string SessionTimedOut {
            get {
                return ResourceManager.GetString("SessionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name is Required..
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is Required.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Updated Successfully..
        /// </summary>
        public static string StatusUpdated {
            get {
                return ResourceManager.GetString("StatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please contact your system administrator..
        /// </summary>
        public static string SystemErrorOccurred {
            get {
                return ResourceManager.GetString("SystemErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assigned Successfully..
        /// </summary>
        public static string TaskAssignedSuccessfully {
            get {
                return ResourceManager.GetString("TaskAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assigning Failed!.
        /// </summary>
        public static string TaskAssigningFailed {
            get {
                return ResourceManager.GetString("TaskAssigningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Date Changed Successfully..
        /// </summary>
        public static string TaskDateChangedSuccessfully {
            get {
                return ResourceManager.GetString("TaskDateChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Date is Requried.
        /// </summary>
        public static string TaskDateRequired {
            get {
                return ResourceManager.GetString("TaskDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Re-Assigned Successfully..
        /// </summary>
        public static string TaskReAssignedSuccessfully {
            get {
                return ResourceManager.GetString("TaskReAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Deleted Successfully..
        /// </summary>
        public static string TechnologyDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TechnologyDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Name is Required..
        /// </summary>
        public static string TechnologyNamerequired {
            get {
                return ResourceManager.GetString("TechnologyNamerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Saved Successfully..
        /// </summary>
        public static string TechnologySavedsuccessfully {
            get {
                return ResourceManager.GetString("TechnologySavedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Updated Successfully..
        /// </summary>
        public static string TechnologyUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TechnologyUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is Required..
        /// </summary>
        public static string Textrequired {
            get {
                return ResourceManager.GetString("Textrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is Required..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date is Required.
        /// </summary>
        public static string ToDateRequired {
            get {
                return ResourceManager.GetString("ToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Email Required..
        /// </summary>
        public static string ToEmailRequired {
            get {
                return ResourceManager.GetString("ToEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added Successfully..
        /// </summary>
        public static string UserAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is no longer active!.
        /// </summary>
        public static string UserNoLongerActive {
            get {
                return ResourceManager.GetString("UserNoLongerActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Updated Successfully..
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have Selected the same File..
        /// </summary>
        public static string YouhaveSelectthesameFile {
            get {
                return ResourceManager.GetString("YouhaveSelectthesameFile", resourceCulture);
            }
        }
    }
}
